---
  - name: Creating unprivileged user
    user:
      name: "{{ user }}"
      state: present
      password: "{{ user_pass }}"

  - name: Updating packages
    apt: 
      update_cache: yes

  - name: Upgrade all packages to the latest version
    apt:
      upgrade: dist

  - name: Installing Required packages
    apt: name={{ item }} state=latest
    with_items:
      - build-essential
      - git
      - ufw

  - name: Add authorized key
    authorized_key:
      user: "{{ user }}"
      state: present
      key: "{{ item }}"
    with_items:
      - "{{ key_url }}"
      - "{{ lookup('file', deploy_key_pub ) }}"

  - name: Copying Github deploy key
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ item.owner }}"
      group: "{{ item.owner }}"
      mode: '600'
    with_items:
      - dest: /root/.ssh/id_rsa
        src: "{{ deploy_key }}"
        owner: root
      - dest: "/home/{{ user }}/.ssh/id_rsa"
        src: "{{ deploy_key }}"
        owner: "{{ user }}"


  - include: iptables.yml
