---
- name: Created nodeapp service
  template:
    src: templates/nodeapp.j2
    dest: /etc/systemd/system/nodeapp.service
    owner: root
    group: root

- name: Created ssh tunnel service
  template:
    src: templates/tunnel.j2
    dest: /etc/systemd/system/tunnel.service
    owner: root
    group: root

- name: Adding ssh tunnel service to boot
  systemd:
    enabled: yes
    name: tunnel
    state: started

- name: Adding nodeapp service to boot
  systemd:
    enabled: yes
    name: nodeapp
    state: restarted
  notify:
    - restart-haproxy

