---

- name: Remove existing web dir
  file:
    state: absent
    path: /var/www

- name: Cloning app repo
  git:
    repo: "{{ app_repo }}"
    dest: /var/www
    accept_hostkey: yes

- name: Apply settings
  replace:
    path: /var/www/settings.js
    regexp: "{{ item.template }}"
    replace: "{{ item.value }}"
  with_items: "{{ api_settings }}"

- name: Running npm install
  npm:
    path: /var/www
