---
  - name: Installing Required packages
    apt: name={{ item }} state=latest
    with_items:
      - apt-transport-https
      - python-openssl
      - nodejs
      - npm
      - graphicsmagick

  - include: haproxy.yml
  - include: letsencrypt-dns.yml
  - include: deploy.yml
  - include: daemonize-nodeapp.yml
