---
- name: Set privileges
  postgresql_privs:
    roles: "{{ item.roles }}"
    priv: "{{ item.privs | default(omit) }}"
    objs: "{{ item.objs | default(omit) }}"
    type: "{{ item.type | default(omit) }}"
    schema: "{{ item.schema | default(omit) }}"
    database: "{{ item.db | default(omit) }}"
    login_host: "{{ item.login_host | default('localhost') }}"
    login_password: "{{ item.login_password | default(omit) }}"
    login_user: "{{ item.login_user | default(postgresql_user) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(postgresql_unix_socket_directories[0]) }}"
    port: "{{ item.port | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ postgresql_privs }}"
  become: true
  become_user: "{{ postgresql_user }}"
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true
